// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1lgBeo4uldgzjpTWCQscSlloEA8I8O50',
    appId: '1:555048034205:web:ab14be9410d61b86d65974',
    messagingSenderId: '555048034205',
    projectId: 'velbislabwork3c',
    authDomain: 'velbislabwork3c.firebaseapp.com',
    storageBucket: 'velbislabwork3c.appspot.com',
    measurementId: 'G-6RXJSDNG1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFy8IRUN8RciONWS0X7rkCcFxMZh1-ito',
    appId: '1:555048034205:android:e120cd98e451d849d65974',
    messagingSenderId: '555048034205',
    projectId: 'velbislabwork3c',
    storageBucket: 'velbislabwork3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt0hSBx_HQo19yFEuooO3DxR1TNYZsb7w',
    appId: '1:555048034205:ios:31ae8e3ca7f6f20ed65974',
    messagingSenderId: '555048034205',
    projectId: 'velbislabwork3c',
    storageBucket: 'velbislabwork3c.appspot.com',
    iosBundleId: 'com.example.velbisLabwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt0hSBx_HQo19yFEuooO3DxR1TNYZsb7w',
    appId: '1:555048034205:ios:d96f7d32076d3848d65974',
    messagingSenderId: '555048034205',
    projectId: 'velbislabwork3c',
    storageBucket: 'velbislabwork3c.appspot.com',
    iosBundleId: 'com.example.velbisLabwork.RunnerTests',
  );
}
